### PR TITLE
Snpprot 78

### PR DESCRIPTION
**Pull request by jlgrock**
Finishing up HK2 work.  This has been tested using both the @HK2 annotation in test cases and using the integration test package (which you can run the individual file using `mvn install exec:java -Dexec.mainClass="com.github.jlgrock.hk2test.TestFoo"` on whatever class you wish.  I have also created a small suite of connection objects for future use, but was unable to test them because it will actually reach out and use MongoDB.  I'll have to do this in the integration testing package at a later point.  Also, there are a number of TODOs, which I will be turning into issues soon.

### CODE REVIEW

**Comment by jlgrock** [comment]
Please note that this won't compile with code Quality due to the web module (which Shane is working on) and the comments are missing from the new Impl classes that I provided to Vikram.  Otherwise, it does compile and pass code quality standards.

**Comment by jlgrock** [comment]
I can make that change.  Probably a good idea.  Note that I have 0 control of the library "DB" object

**Comment by shalewis** [comment]
I've reviewed the changes and they look good for merging with the one exception of following proper camel casing of the 'database' abbreviation of 'Db'.

**Comment by jlgrock** [comment]
Oh, I've noted this in the issue, but this is actually for SNPPROT-76, I just put the wrong issue # on it.  Also, fixed your suggestion.

**Comment by jlgrock** [comment]
k, there were some issues with the automatic merge not taking the file renames, but otherwise was successful.  closing.

**Pull request merged**
